name: Publish and Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    env:
      python_ver: 3.13.1
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.python_ver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_ver }}
    
      - name: Run generator file
        run: python generate_plugin_file.py

      - name: Install Plugin dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Build Error UI
        run: build_error_ui.bat

      - name: Get Plugin's version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "plugin.json"
          prop_path: "Version"
      
      - name: Archive Release
        run: |
          python create_build_archive.py ${{ github.event.repository.name }}.zip
        
      - name: Publish
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: '${{ github.event.repository.name }}.zip'
          tag_name: "v${{steps.version.outputs.prop}}"
          body_path: 'CHANGELOG.txt'
